### ISSUE TITLE
Section 7: Cluster Setup - Secure Ingress

### ISSUE THREAD

**Issue by rh0dy** [killer-sh/cks-course-environment#17]
During the "Section 7: Cluster Setup - Secure Ingress > Practice - Create Ingress" lecture, we created an Ingress resource with 2 paths to `service1` and `service2`.  

I had an issue resolving these routes. For example, `curl http://<node IP>:<node port>/service1`would display the nginx standard 404 message instead of the welcome text.  

To resolve this, the [NGINX Ingress Controller ](https://kubernetes.github.io/ingress-nginx/user-guide/basic-usage/) docs state that the `kubernetes.io/ingress.class: "nginx"` annotation needs to be added to our Ingress resource, which makes it discoverable by NGINX Ingress:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: secure-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:
      - path: /service1
        pathType: Prefix
        backend:
          service:
            name: service1
            port:
              number: 80
      - path: /service2
        pathType: Prefix
        backend:
          service:
            name: service2
            port:
              number: 80
```

It might be worth testing this yourself to see if it's a general problem (not just one for me).
