### ISSUE TITLE
Network Polices Lecure:21

### ISSUE THREAD

**Issue by ldynia** [killer-sh/cks-course-environment#2]
I really liked the example. It would be cool to add video with explenation of the problem and solution for kube-dns and opening port 53 as Amer pointed 

```yaml
apiKind: NetworkPolicy
metadata:
  name: frontend-with-kube-dns
  namespace: default
spec:
  podSelector:
    matchLabels:
      run: frontend
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          run: backend
    ports:
    - protocol: TCP
      port: 80
  - to:
    ports:
    - protocol: UDP
      port: 53
```

**Comment by ldynia** [comment]
Have you manage to do entire example #22 with DNS resolved correctly? frontend>backend>cassandra so that all service names are resolved while doing cur?

**Comment by wuestkamp** [comment]
Hi @ldynia,

I'll update our solution to support DNS resolution during the next days. Will also update the video. It's actually a great suggestion!

I think a good and easy way would be to add this to the default deny policy:
```
  - to:
    ports:
      - port: 53
        protocol: TCP
      - port: 53
        protocol: UDP
```

Or even cleaner: create another NP "allow-dns" which allows this.

Thanks,
Kim
